### ISSUE TITLE
Update to MIMIC-IV v2.2

### ISSUE THREAD

**Issue by USM-CHU-FGuyon** [USM-CHU-FGuyon/BlendedICU#1]
Current version runs on MIMIC-IV v0.4, which is slighlty outdated.

**Comment by xinyuejohn** [comment]
Hi, could you please tell me when are you going to adapt the pipeline for this?

**Comment by USM-CHU-FGuyon** [comment]
Hi, this issue stayed low priority for a while now... I will try to address this within the next two or three weeks

**Comment by USM-CHU-FGuyon** [comment]
update: I expect to release a new version next week that will run on MIMIC-IV v2.2
