### ISSUE TITLE
Potential bug in 3_blendedICU.py

### ISSUE THREAD

**Issue by xinyuejohn** [USM-CHU-FGuyon/BlendedICU#16]
Could you please check if the function is falsely called in `3_blendedICU.py`:

`flp.run_flat_and_labels()`

Because `run_flat_and_labels` has not been declared or implemented (it only appears once here) and the similar function `preprocess_flat_and_labels` was implemented but has not been called.

**Comment by USM-CHU-FGuyon** [comment]
Oh, Sorry for that. I must have messed that up in the last commit. Fixing this now
