### ISSUE TITLE
person_id inconsistent in final OMOP death table

### ISSUE THREAD

**Issue by xinyuejohn** [USM-CHU-FGuyon/BlendedICU#17]
Hi, I reran the pipeline on MIMIC-III using your latest code (v0.2.1) and I found the `person_id` final OMOP `death` table actually contains `visit_occurrence_id`. 

Could you please take a look at this? Thanks!

**Comment by USM-CHU-FGuyon** [comment]
Thanks again for pointing this out ! I will check that `visit_occurrence_id`s and `patient_id`s are properly filled in every table.

**Comment by theompm** [comment]
In `drug_exposure` are missing `patianet_id `s

perhaps this referres to the same issue

**Comment by USM-CHU-FGuyon** [comment]
Thanks for your input, I'm checking other tables soon !
