### ISSUE TITLE
Query on Estimated Running Times Across different Datasets

### ISSUE THREAD

**Issue by xinyuejohn** [USM-CHU-FGuyon/BlendedICU#24]
Could you provide insights or benchmarks regarding the time it takes to run the pipeline with various datasets? Moreover, a progress bar indicating the estimated running time would also be beneficial.

Having an estimate of the running time before initiating the pipeline would be extremely helpful. 

Thank you!

**Comment by USM-CHU-FGuyon** [comment]
Hi, I will definetely add this sometime soon !

**Comment by USM-CHU-FGuyon** [comment]
I did not add a progressbar (yet), but I added estimated running times on most lengthy scripts. I timed this running them all in parallel, so times could be a little overestimated for a single run. Running times may also depend a lot on writing times on specific machines.

Please tell me if you find consistent running times, I never timed this on another machine.
