### ISSUE TITLE
Missing env.yml Runtime Environment Configuration File

### ISSUE THREAD

**Issue by CabinH** [USM-CHU-FGuyon/BlendedICU#5]
I've been following your project on GitHub, and in the **readme.md** file, it mentions the presence of an **env.yml** runtime environment configuration file. However, I couldn't locate this file anywhere within the entire project. I'm hoping to use this file to correctly configure the project's runtime environment. Is it possible to provide some assistance or guidance, or could you please check if there's a location I might have overlooked?

I expected the env.yml file to be in the project's root directory or at the location mentioned in the readme.md. If it's located in a specific subdirectory of the project or follows a particular naming convention, please provide detailed information so that I can locate it.

Thank you very much for your assistance, and I'm looking forward to successfully configuring the project's runtime environment! If there's any additional information or guidance, please do let me know.

**Comment by USM-CHU-FGuyon** [comment]
The env.yml was added in release v0.1.0. Pandas version was bumped to v2.1 and seaborn to v0.13
